const SET_INGREDIENTS = 'SET_INGREDIENTS';
const SET_TOTAL_PRICE = 'SET_TOTAL_PRICE';
const CAN_PURCHASE = 'CAN_PURCHASE';
const IS_PURCHASING = 'IS_PURCHASING';
const UPDATE_PURCHASE = 'UPDATE_PURCHASE';
const ERROR = 'ERROR';

export default {
  SET_INGREDIENTS,
  SET_TOTAL_PRICE,
  CAN_PURCHASE,
  IS_PURCHASING,
  UPDATE_PURCHASE,
  ERROR
};
